<?php

/**
 * Generated by Muhammad Muflih Kholidin
 * https://github.com/mmuflih
 * muflic.24@gmail.com
 **/

namespace App\Console\Commands;

use App\Context\MailEngine\SendHandler;
use Carbon\Carbon;
use Illuminate\Console\Command;

class SendEmailCommand extends Command
{
	protected $name = "send:mail";

	public function handle()
	{
		$now = Carbon::now()->timestamp;
		$handler = new SendHandler();
		$handler->send("muflic.24@gmail.com", "Jon", "909009");
	}
}
