<?php

/**
 * Generated by Muhammad Muflih Kholidin
 * https://github.com/mmuflih
 * muflic.24@gmail.com
 **/

namespace App\Context\MenuController;

use Carbon\Carbon;

class MenuAccess
{
    private static $path = "tmp/access";

    public static function save($id, $data = [])
    {
        if (!is_dir(self::$path)) {
            mkdir(self::$path, 0777, true);
        }

        $data = json_encode($data);

        return file_put_contents(self::$path . "/uac-$id", $data);
    }

    public static function get($id)
    {
        $data = file_get_contents(self::$path . "/uac-$id");
        return json_decode($data, true);
    }
}
