<?php

/**
 * Generated by Muhammad Muflih Kholidin
 * https://github.com/mmuflih
 * muflic.24@gmail.com
 **/

namespace App\Context\MailEngine;

use App\Context\Handler;
use Illuminate\Support\Facades\Mail;

class SendHandler implements Handler
{
	public function __construct()
	{
	}

	public function handle()
	{
	}

	public function send($to, $toName, $subject, $blade, $data)
	{
		Mail::send($blade, $data, function ($message) use ($toName, $to, $subject) {
			$message->to($to, $toName)
				->subject($subject);
			$message->from(env('MAIL_FROM_ADDRESS'), env('MAIL_FROM_NAME'));
		});
	}
}
