<?php

/**
 * Generated by Muhammad Muflih Kholidin
 * https://github.com/mmuflih
 * muflic.24@gmail.com
 **/

namespace App\Context;

class ContextException
{
	public static function unauthenticatedUser()
	{
		throw new \Exception("Untauthenticated User", 422);
	}

	public static function dataNotFound($data)
	{
		throw new \Exception("$data data not found", 422);
	}
}
