<?php

/**
 * Generated by Muhammad Muflih Kholidin
 * https://github.com/mmuflih
 * muflic.24@gmail.com
 **/

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Control extends Model
{
    public static $TYPE_IMPORT = "imp";
    public static $TYPE_EXPORT = "exp";
    public static $TYPE_CUKAI_MMEA = "cmm";
    public static $TYPE_CUKAI_HT = "cht";
    public static $TYPE_CUKAI_EA = "cea";

    protected $table = "controls";

    protected $fillable = [
        'sbp', 'total', 'follow_up', 'item_value', 'input_date', 'type',
        'division_id', 'name', 'loss_value', 'user_id'
    ];
}
