<?php

/**
 * Generated by Muhammad Muflih Kholidin
 * https://github.com/mmuflih
 * muflic.24@gmail.com
 **/

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class CukaiHtHptlCompany extends Model
{
    protected $table = "cukai_ht_hptl_companies";

    protected $fillable = [
        'name', 'ck_amount', 'amount_of_excise_duty', 'user_id', 'input_date',
        'division_id', 'nppbkc', 'bkc_type', 'amount', 'tax_amount'
    ];
}
