<?php

/**
 * Generated by Muhammad Muflih Kholidin
 * https://github.com/mmuflih
 * muflic.24@gmail.com
 **/

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class CukaiMMEACompany extends Model
{
    protected $table = "cukai_mmea_companies";

    protected $fillable = [
        'name', 'number_of_documents', 'number_of_liters', 'amount_of_excise_duty',
        'user_id', 'input_date', 'division_id', 'nppbkc'
    ];
}
