<?php

/**
 * Generated by Muhammad Muflih Kholidin
 * https://github.com/mmuflih
 * muflic.24@gmail.com
 **/

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class DivisionGallery extends Model
{
    public static $TYPE_GALLERY = 'gl';
    public static $TYPE_DISTRIBUTION_MAP = 'dm';
    public static $TYPE_VULNERABILITY_MAP = 'vm';

    protected $table = 'division_galleries';

    protected $fillable = [
        'url', 'uri', 'division_id', 'mime_type', 'description',
        'type', 'title'
    ];

    protected $casts = [
        'ed' => 'boolean'
    ];
}
