<?php

/**
 * Generated by Muhammad Muflih Kholidin
 * https://github.com/mmuflih
 * muflic.24@gmail.com
 **/

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class DivisionProfile extends Model
{
    protected $table = 'division_profiles';

    protected $fillable = ['division_id', 'description', 'activity', 'surveillance_area'];
}
