<?php

/**
 * Generated by Muhammad Muflih Kholidin
 * https://github.com/mmuflih
 * muflic.24@gmail.com
 **/

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Division extends Model
{
    protected $table = "divisions";

    protected $fillable = ['name', 'slug', 'seq'];

    public function profile()
    {
        return $this->hasOne(DivisionProfile::class);
    }

    public function galleries()
    {
        return $this->hasMany(DivisionGallery::class);
    }
}
