<?php

/**
 * Generated by Muhammad Muflih Kholidin
 * https://github.com/mmuflih
 * muflic.24@gmail.com
 **/

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class EmailVerification extends Model
{
    protected $table = "email_verifications";

    protected $fillable = [
        'email', 'token', 'expired_at', 'request_remaining', 'verified', 'division_id'
    ];
}
