<?php

/**
 * Generated by Muhammad Muflih Kholidin
 * https://github.com/mmuflih
 * muflic.24@gmail.com
 **/

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class ExportCompany extends Model
{
    protected $table = "export_companies";

    protected $fillable = [
        'name', 'peb', 'devisa', 'export_duty', 'netto', 'user_id',
        'input_date', 'division_id', 'tax_number', 'bruto', 'exit_duty'
    ];
}
