<?php

/**
 * Generated by Muhammad Muflih Kholidin
 * https://github.com/mmuflih
 * muflic.24@gmail.com
 **/

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class OperatingOther extends Model
{
    protected $table = "operating_others";

    protected $fillable = [
        'type_of_operation',
        'type',
        'placement_location',
        'condition',
        'notes',
        'input_date', 'division_id',
        'user_id'
    ];
}
