<?php

/**
 * Generated by Muhammad Muflih Kholidin
 * https://github.com/mmuflih
 * muflic.24@gmail.com
 **/

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class OperatingFirearm extends Model
{
    protected $table = "operating_firearms";

    protected $fillable = [
        'caliber_type',
        'weapon_number',
        'pass_book_number',
        'validity_period',
        'condition',
        'weapon_holder_name',
        'weapon_holder_rank',
        'weapon_holder_position',
        'ammo_amount',
        'notes',
        'input_date', 'division_id',
        'user_id'
    ];
}
