<?php

/**
 * Generated by Muhammad Muflih Kholidin
 * https://github.com/mmuflih
 * muflic.24@gmail.com
 **/

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class OperationPatrolBoat extends Model
{
    protected $table = "operating_patrol_boats";

    protected $fillable = [
        'hull_number',
        'condition',
        'spb_number',
        'spb_date',
        'spb_publisher',
        'day_amount',
        'notes',
        'input_date',
        'user_id',
        'division_id'
    ];
}
