<?php

/**
 * Generated by Muhammad Muflih Kholidin
 * https://github.com/mmuflih
 * muflic.24@gmail.com
 **/

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class OperatingScanner extends Model
{
    protected $table = "operating_scanners";

    protected $fillable = [
        'scanner',
        'name',
        'tool_size',
        'brand',
        'type',
        'serial_number',
        'singgle_dual_view',
        'year_of_acquisition',
        'condition',
        'placement_location',
        'operating_hours',
        'scan_hours',
        'number_of_scans',
        'output',
        'notes',
        'input_date', 'division_id',
        'user_id'
    ];
}
