<?php

/**
 * Generated by Muhammad Muflih Kholidin
 * https://github.com/mmuflih
 * muflic.24@gmail.com
 **/

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class OperatingTelecomunicationTools extends Model
{
    protected $table = "operating_telecomunication_tools";

    protected $fillable = [
        'device_type',
        'acquisition_cost',
        'year_of_acquisition',
        'brand',
        'type',
        'frequency_range',
        'digital_technology',
        'condition',
        'status',
        'placement_location',
        'notes',
        'code',
        'nup',
        'name',
        'input_date',
        'division_id',
        'user_id'
    ];
}
