<?php

/**
 * Generated by Muhammad Muflih Kholidin
 * https://github.com/mmuflih
 * muflic.24@gmail.com
 **/

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Receipt extends Model
{
    protected $table = "receipts";

    protected $fillable = [
        // 'achievement_target', 'achievements', 'percentage',
        'target_import_duty',
        'target_export_duty',
        'target_tax',
        'realization_import_duty',
        'realization_export_duty',
        'realization_tax',
        'input_date',
        'division_id',
        'user_id'
    ];

    protected $casts = [
        'target_export_duty' => 'float',
        'target_tax' => 'float',
        'realization_import_duty' => 'float',
        'realization_export_duty' => 'float',
        'realization_tax' => 'float',
        'input_date' => 'float',
        'realization_total' => 'float',
        'target_total' => 'float',
        'target_import_duty' => 'float'
    ];
}
