<?php

/**
 * Generated by Muhammad Muflih Kholidin
 * https://github.com/mmuflih
 * muflic.24@gmail.com
 **/

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Sbp extends Model
{
    protected $table = 'sbps';

    protected $fillable = ['division_id', 'amount', 'follow_up', 'input_date'];
}
