<?php

/**
 * Generated by Muhammad Muflih Kholidin
 * https://github.com/mmuflih
 * muflic.24@gmail.com
 **/

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Crypt;

class UserPassword extends Model
{
    protected $table = "user_passwords";
    protected $fillable = ['user_id', 'password', 'active'];

    public function setPassword($text)
    {
        $this->password = app('hash')->make($text);
    }
}
